version: '3.8'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-standalone
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-ui-network

networks:
  kafka-ui-network:
    driver: bridge
